import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat autem perspiciatis officiis eaque sunt assumenda, maxime repellat? Omnis libero cupiditate iure? Dicta harum nam ab, veritatis labore deleniti perferendis vel.</p>
  )
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-32">
        {children}
        </div>

        <LoginModal />
        <SignupModal />
      </body>
    </html>
  );
}
